name: chat_gpt_02
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  bubble: ^1.2.1
  get: 4.6.5
  dio: ^4.0.6


dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

